export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ESTATE_ADMIN = 'ESTATE_ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  GUARD = 'GUARD',
  RESIDENT = 'RESIDENT',
}

export enum VisitStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  EXPIRED = 'EXPIRED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  REVOKED = 'REVOKED',
  OVERRIDE_ADMITTED = 'OVERRIDE_ADMITTED',
}

export enum MessageSendState {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}

export enum DecisionValue {
  APPROVE = 'APPROVE',
  DENY = 'DENY',
}

export enum DecisionChannel {
  WHATSAPP_BUTTON = 'WHATSAPP_BUTTON',
  WEB_LINK = 'WEB_LINK',
}

export enum VerificationMethod {
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  PHYSICAL_RECOGNITION = 'PHYSICAL_RECOGNITION',
  PHONE_CALL_CONFIRMED = 'PHONE_CALL_CONFIRMED',
  SUPERVISOR_EXCEPTION = 'SUPERVISOR_EXCEPTION',
}

export enum ConsentSource {
  ADMIN_PORTAL = 'ADMIN_PORTAL',
  SMS_INVITE = 'SMS_INVITE',
  QR_CODE = 'QR_CODE',
  PAPER_FORM = 'PAPER_FORM',
}

export enum WebhookProcessingState {
  RECEIVED = 'RECEIVED',
  PROCESSED = 'PROCESSED',
  IGNORED = 'IGNORED',
  FAILED = 'FAILED',
}
